gemfile: Gemfile

PreCommit:
  # Disabled since this causes spurious failures on AppVeyor builds
  BrokenSymlinks:
    enabled: false

  BundleCheck:
    enabled: true

  ExecutePermissions:
    enabled: true
    exclude:
      - 'bin/overcommit'
      - 'libexec/**/*'
      - 'template-dir/hooks/**/*'

  HardTabs:
    enabled: true

  MasterHooksMatch:
    enabled: true
    quiet: true

  RuboCop: &rubocop
    enabled: true
    include:
      - '**/*.gemspec'
      - '**/*.rb'
      - '**/Gemfile'
      - template-dir/hooks/overcommit-hook

  TrailingWhitespace:
    enabled: true

  YamlSyntax:
    enabled: true

PrePush:
  RuboCop: *rubocop
